### ISSUE TITLE
[Package Request] Packages needed for Summit XL

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-desktop-full#13]
It seems like ROS is calling me back lol.
Anyway working on a different system and would like to request to following packages and the associated deps:

- [x] [ros-melodic-summit-xl-common](https://github.com/RobotnikAutomation/summit_xl_common)
- [x] [ros-melodic-summit-xl-control](https://github.com/RobotnikAutomation/summit_xl_common)
- [x] [ros-melodic-summit-xl-description](https://github.com/RobotnikAutomation/summit_xl_common)
- [x] [ros-melodic-summit-xl-localization](https://github.com/RobotnikAutomation/summit_xl_common)
- [x] [ros-melodic-summit-xl-navigatoin](https://github.com/RobotnikAutomation/summit_xl_common)
- [x] [ros-melodic-summit-xl-pad](https://github.com/RobotnikAutomation/summit_xl_common)
- [x] [ros-melodic-summit-xl-sim](https://github.com/RobotnikAutomation/summit_xl_sim)
- [x] [ros-melodic-summit-xl-sim-bringup](https://github.com/RobotnikAutomation/summit_xl_sim)
- [x] [ros-melodic-summit-xl-gazebo](https://github.com/RobotnikAutomation/summit_xl_sim)
- [x] [ros-melodic-robotnik-sensors](https://github.com/RobotnikAutomation/robotnik_sensors)
- [x] [ros-melodic-hector-gazebo-plugins](https://github.com/tu-darmstadt-ros-pkg/hector_gazebo)
- [x] [ros-melodic-costmap-prohibition-layer](https://github.com/rst-tu-dortmund/costmap_prohibition_layer)

Will close once they get pushed to AUR.

**Comment by acxz** [comment]
Created the packages and transferred ownership to you @bionade24

**Comment by bionade24** [comment]
Thanks, no problem. I'm very busy ATM because I have a presentation soon & and wouldn't have done it until Wednesday.

**Comment by acxz** [comment]
No worries and Good Luck!!!
