### ISSUE TITLE
[Package Request] Packages needed for CrazyS

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-desktop-full#14]
Working on another system/simulator now and need the following packages to get up and running with CrazyS:

- [x] [ros-melodic-mav-planning-msgs](https://github.com/ethz-asl/mav_comm)
- [x] [ros-melodic-mav-msgs](https://github.com/ethz-asl/mav_comm)
- [x] [ros-melodic-rotors-comm](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rotors-control](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rotors-description](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rotors-gazebo](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rotors-gazebo-plugins](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rotors-evaluation](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rotors-hil-interface](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rotors-joy-interface](https://github.com/ethz-asl/rotors_simulator)
- [x] [ros-melodic-rqt-rotors](https://github.com/ethz-asl/rotors_simulator)

As usual, will close once packages get synced to the AUR.

**Comment by lilioid** [comment]
`python-catkin-tools` does not work under python3 in its current release.
Fixes are already merged but not released.

For that reason there is a `python-catkin-tools-git` package available in the AUR ;)

**Comment by acxz** [comment]
Ah I see, eventually we would like a release package from them though right?
Edit: it seems like @kartikmohta is maintaining [`python-catkin_tools`](https://aur.archlinux.org/packages/python-catkin_tools) my bad flew under my radar.

Also I notice you maintain some ROS2 packages. Would you be interested in making an organization like this one for ROS2, eventually I want to move over to ROS2, but right now that is difficult to do on Arch without something similar to this organization. @bionade24  @jwhendy  would you guys be interested in this as well?

**Comment by jwhendy** [comment]
Is the `catkin_tools` issue new? I haven't used ROS in maybe a month, but definitely used `catkin build` for my compiling with no problem.

Re. ROS2, I think the more the merrier. For my use-cases at work, we haven't switched to ROS2, but I'm guessing everyone will be at some point?

**Comment by jwhendy** [comment]
Ah, just kidding. If it was the `asyncio` issue, I did run into that and probably just don't recall that I installed from source. I'm still recovering from a fresh install after hard drive issues and haven't gotten ROS setup again.

**Comment by acxz** [comment]
EOL for the latest ROS1 is May, 2025, so we still have some ways to go, but eventually ROS2 will supersede ROS1. For me, as I move along in my research I will be working on safety critical systems and will need the real-time support, which is why I want to get on ROS2 as fast as possible.

**Comment by acxz** [comment]
Packages pushed to AUR and under @bionade24's ownership.

**Comment by lilioid** [comment]
> Ah I see, eventually we would like a release package from them though right?

sure, as soon as they release it

> Also I notice you maintain some ROS2 packages. Would you be interested in making an organization like this one for ROS2, eventually I want to move over to ROS2, but right now that is difficult to do on Arch without something similar to this organization. @bionade24 @jwhendy would you guys be interested in this as well?

that idea did come to mind and I might do it at some point. But like others my people are currently stillt working with Ros1 so we don't really need it yet. We'll likely switch to Ros2 maybe a year from now so I'll reconsider doing it at that time.
Of course I would be happy to collaborate with others especially since I don't have as much experience maintaining packages.

**Comment by bionade24** [comment]
> Packages pushed to AUR and under @bionade24's ownership.
Please leave me some time to add them in the CI. I currently don't have time to do this. Did you create the github Repos, too?

**Comment by acxz** [comment]
@ftsell that sounds great, will definitely remember you when we get around to it. Looking forward to it!

I was also thinking instead of having all of these ros-<distro_name>-package-name to have just ros-package-name, since Arch follows the latest release anyway. The distinction should be makde for ROS 1 and ROS 2 though, but for individual distro releases like melodic vs noetic and dashing vs eloquent, we don’t really care right, since we will be hopping onto the new release anyway. As such I think when we create the ros2 packages we should just the name them as ros-package-name. Infact debian does this already with their ROS packages available from the debian repos.

@bionade24 yep!

**Comment by bionade24** [comment]
> @ftsell that sounds great, will definitely remember you when we get around to it. Looking forward to it!
> 
> I was also thinking instead of having all of these ros-<distro_name>-package-name to have just ros-package-name, since Arch follows the latest release anyway. The distinction should be makde for ROS 1 and ROS 2 though, but for individual distro releases like melodic vs noetic and dashing vs eloquent, we don’t really care right, since we will be hopping onto the new release anyway. As such I think when we create the ros2 packages we should just the name them as ros-package-name. Infact debian does this already with their ROS packages available from the debian repos.
> 
> @bionade24 yep!

I think it's a way to big effort to package the non-LTS releases. I also think that most people stay on the LTS distros. So as this maybe makes sense on Debian, but I don't think that's a good idea for arch.

**Comment by acxz** [comment]
But how can we differentiate between LTS and non-LTS releases of packages from the upstream repository releases? I don't think that is possible unless the person updating each package does his due diligence in finding that out. We are at latest release anyway, what difference would LTS and non-LTS of a package make? In fact when Noetic comes around are we going to have to create an entire different organization just because of the name change? When in reality the only change that happens is bumping up a release version.

Of course Noetic is a different story, since ROS2 is already out so for that release, we will need to create an organization like we did for melodic. But in the future do we want to do that for every new ROS2 release? Thats seems like a lot more work than just keeping up with the latest release.
Sure we can use rosindex and rosdistro like @jwhendy has been playing around with, but I creating these huge amount of packages for every release instead of sticking with just ros-package-name seems to be quite time-consuming.

**Comment by bionade24** [comment]
Ok, let's focus on ROS2. Tell me if I'm wrong because ROS2 changed something fundamentally, but I just want to give you a view why most people use the Distro Releases. You have for a specific distro optimized packages or use some proprietary ABI that doesn't work with the new release. Then you can stay longer on a specific distro until everything is fixed. Otherwise people would scream all the time because  they lost their packages don't work after an update? Or maybe certain packages never make it to the new release? Do you then want to tell those people to simply not update? I think to have a reliable ROS setup, distro specific packages are important.

**Comment by acxz** [comment]
This is true, yeah I am now convinced of having the LTS releases. It is just that now it will be important that we do not update packages to versions higher than the self-reported ones on rosindex for a given distribution. This will put us at a slower release cycle than upstream and can cause us to make more patches than necessary.
Don't get me wrong, I do think have the latest LTS release is important, but ideally having both the latest LTS release and latest upstream release would be nice. Although that is just more work to maintain.

**Comment by bionade24** [comment]
> This is true, yeah I am now convinced of having the LTS releases. It is just that now it will be important that we do not update packages to versions higher than the self-reported ones on rosindex for a given distribution. This will put us at a slower release cycle than upstream and can cause us to more patches than necessary.
> Don't get me wrong, I do think have the latest LTS release is important, but ideally having both the latest LTS release and latest upstream release would be nice. Although that is just more work to maintain.

When noetic gets released in May we'll package it for sure. Once the tools work properly (and we have a faster build testing server) it shouldn't be a real problems. Maybe how this works should be reelaborated and we should find some way on some other CI program to base on and write our tools somehow better. It's really sad that OSRF doesn't really care about other distros, even if their own devs are using it.

**Comment by acxz** [comment]
Sounds good, I am glad we had this conversation. :smile:

**Comment by bionade24** [comment]
The problem is just what CI to use. All free CIs are slow as hell, even the new Github CI has often timeouts. So only drone, jenkins & Gitlab CI remain, for all we need a dedicated server. If this should work well in long-term someone has to sponsor a mid-powered server (8cores /32GB RAM) only for this.
