### ISSUE TITLE
fix pkgbuild url links

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-desktop-full#17]
Based on Repology a lot of our packages have dead links. Just some housekeeping, but it's nice to get these fixed up.

https://repology.org/maintainer/bionade24%40aur/problems

**Comment by acxz** [comment]
@jwhendy do you think you can handle this? I remember you had a nifty script for this.

**Comment by jwhendy** [comment]
I'll revisit. I *did*, but in a hard drive issue/complete re-install, I did not grab that scripts folder and did not have it backed up. I can still look.

**Comment by jwhendy** [comment]
Geez. Good lord, that's all my fault anyway. My former script looks to have added www to almost every URL, which is why they don't resolve.

**Comment by acxz** [comment]
riiiiip lol

**Comment by bionade24** [comment]
I included the script here and fixed some problems: https://github.com/bionade24/aur-ci/blob/master/aurci/update.py
