### ISSUE TITLE
OpenCV versions

### ISSUE THREAD

**Issue by MalcolmMielle** [ros-melodic-arch/ros-melodic-desktop-full#20]
I'm not sure where to ask my question so please redirect me and close this issue if it's the wrong channel.

I've tried installing ROS on arch for the first time and I also have opencv already installed on my machine (v4) from before. I see during the build that ros libraries are sometime pulling the v4 version of opencv and sometime the opencv-opt version (which is the current version associated with melodic if I got it correctly). So I have multiple question about this:

* Is there a way to use the more recent opencv version and ignore/not install opencv-opt?
* Can I have both package on my machine (opencv and opencv-opt), or are they incompatible?

Thanks,

**Comment by jwhendy** [comment]
Bedtime reading for you :)

- https://github.com/ros-melodic-arch/ros-melodic-image-geometry/issues/1
- https://github.com/ros-melodic-arch/ros-melodic-cv-bridge/issues/6
- https://github.com/ros-perception/vision_opencv/issues/272

**Comment by MalcolmMielle** [comment]
Super! Good that tomorrow is a day off ;)

**Comment by acxz** [comment]
Considering that this issue is reflected with existing issues/PRs can we go ahead and close this @MalcolmMielle ?

**Comment by MalcolmMielle** [comment]
Sure !
