### ISSUE TITLE
[Package Request] ros-melodic-moveit-ros-occupancy-map-monitor

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-desktop-full#21]
Repo:
https://github.com/ros-planning/moveit

Package:
https://github.com/ros-planning/moveit/tree/master/moveit_ros/occupancy_map_monitor

I've already got a PKGBUILD in place: https://github.com/fmauch/PKGBUILDs/blob/master/moveit_ros_occupancy_map_monitor/PKGBUILD

- [x] ros-melodic-moveit-ros-occupancy-map-monitor

**Comment by acxz** [comment]
A repo has been created for the package, feel free to submit PRs to it and we will get it synced to the AUR

https://github.com/ros-melodic-arch/ros-melodic-moveit-ros-occupancy-map-monitor

**Comment by fmauch** [comment]
It seems like I can neither fork the repository nor create a PR from another place, as the repository is completely empty. Am I missing something? Is there a way to workaround this?

**Comment by acxz** [comment]
Sorry about that, created some empty files give it a go now

**Comment by acxz** [comment]
pushed to AUR
