### ISSUE TITLE
[Package Request] franka emika pakcages

### ISSUE THREAD

**Issue by liborw** [ros-melodic-arch/ros-melodic-desktop-full#22]
Hi,

I have created packages for franka emika robot:

https://github.com/frankaemika/franka_ros:
- [x] ros-melodic-franka-control
- [x] ros-melodic-franka-description
- [x] ros-melodic-franka-example-controllers
- [x] ros-melodic-franka-gripper
- [x] ros-melodic-franka-hw
- [x] ros-melodic-franka-msgs
- [x] ros-melodic-franka-ros
- [x] ros-melodic-franka-visualization

https://github.com/frankaemika/libfranka:
- [x] ros-melodic-libfranka

https://github.com/ros-planning/panda_moveit_config:
- [x] ros-melodic-panda-moveit-config

How can I add them here?

**Comment by acxz** [comment]
I'll go ahead and create the associated repos and then you can submit PRs to these repos.

EDIT: Repos have been created, feel free to submit your PKGBUILDs as PRs and we will get them merged and synced.

This issue will be closed until we get these packages out on the AUR.

**Comment by liborw** [comment]
Ok, should I use the release repository (https://github.com/frankaemika/franka_ros-release) or the base (https://github.com/frankaemika/franka_ros) ?

**Comment by acxz** [comment]
I believe the base is the one we should use.

**Comment by liborw** [comment]
Ok

**Comment by liborw** [comment]
There will be one more ros-melodic-panda-moveit-config

**Comment by acxz** [comment]
Added the associated repo for [`ros-melodic-panda-moveit-config`](https://github.com/ros-melodic-arch/ros-melodic-panda-moveit-config)

**Comment by fmauch** [comment]
I've filled the associated packages with content and created the AUR packages. Therefore, closing this.
