### ISSUE TITLE
[Package Request] trac-ik

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-desktop-full#23]
https://bitbucket.org/traclabs/trac_ik/src/master/

Packages:
 - [x] trac_ik (https://github.com/ros-melodic-arch/ros-melodic-trac-ik/pull/1)
 - [x] trac_ik_examples (https://github.com/ros-melodic-arch/ros-melodic-trac-ik-examples/pull/1)
 - [x] trac_ik_kinematics_plugin (https://github.com/ros-melodic-arch/ros-melodic-trac-ik-kinematics-plugin/pull/1)
 - [x] trac_ik_lib
 - [x] trac_ik_python (https://github.com/ros-melodic-arch/ros-melodic-trac-ik-python/pull/1)

I've got PKGBUILDs in place to create PRs once the repos are there.

**Comment by acxz** [comment]
The associated repos have been created

**Comment by fmauch** [comment]
Sorry, I missed the most important one: trac_ik_lib

**Comment by fmauch** [comment]
Updated all mentioned repositories, created AUR packages anf handed them over to @bionade24. All done here.
