### ISSUE TITLE
[Package Request] missing controllers

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-desktop-full#24]
https://github.com/ros-controls/ros_controllers

- [x] ackermann-steering-controller (https://github.com/ros-melodic-arch/ros-melodic-ackermann-steering-controller/pull/1)
- [x] force_torque_sensor_controller (https://github.com/ros-melodic-arch/ros-melodic-force-torque-sensor-controller/pull/1)
- [x] gripper_action_controller (https://github.com/ros-melodic-arch/ros-melodic-gripper-action-controller/pull/1)
- [x] imu_sensor_controller (https://github.com/ros-melodic-arch/ros-melodic-imu-sensor-controller/pull/1)
- [x] joint_trajectory_controller (https://github.com/ros-melodic-arch/ros-melodic-joint-trajectory-controller/pull/1)
- [x] ros_controllers (https://github.com/ros-melodic-arch/ros-melodic-ros-controllers/pull/1)
- [x] rqt_joint_trajectory_controller (https://github.com/ros-melodic-arch/ros-melodic-rqt-joint-trajectory-controller/pull/1)

I've already got a PKGBUILD for some of them and I could provide the others.

**Comment by acxz** [comment]
Added the associated repos

**Comment by fmauch** [comment]
@bionade24 I fixed all the mentioned packages, created associated AUR packages and added you as co-maintainer. Next step as explained [here](https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/27#issuecomment-664045212) would be to disown them, so you will be proper maintainer of those packages, is that correct?

**Comment by bionade24** [comment]
Yes. Then the owner automatically changes.

**Comment by bionade24** [comment]
> Yes. Then the owner automatically changes.

Thx for your work.

**Comment by fmauch** [comment]
Done. I'll close this then, as everything here is done from my point of view :-)
