### ISSUE TITLE
up-to-date status page

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-desktop-full#26]
Since switching to archlinux I find it to be a bit tedious to check which ROS packages are available and whether those are up-to-date in the AUR.

Is there some status overview / scripting for this? Otherwise I might be willing to create a scripting tool for this. The idea would basically be to compare the `ros-melodic-*`-packages in AUR with the one listed in the rosdistro.

I opened the issue here, as this seems to be the most generic place.

**Comment by acxz** [comment]
@fmauch sorry for not personally telling you this but we have shifted our operations over to the [ros-noetic-arch](https://github.com/ros-noetic-arch) github org. See: https://discourse.ros.org/t/who-is-using-ros-on-archlinux/388/66?u=acxz
Feel free to open up the package requests there and help out over there

**Comment by fmauch** [comment]
closing this in favor of https://github.com/ros-noetic-arch/ros-noetic-desktop-full/issues/9
