### ISSUE TITLE
Installation fails on Manjaro 20.0.3

### ISSUE THREAD

**Issue by selmadani** [ros-melodic-arch/ros-melodic-desktop-full#28]
Hello,
im trying to install ros melodic desktop full. The installation process fails after awhile. I have manjaro 20.0.3 below is the error that im getting! any help would be appreciated.  Thank you!
-- Build files have been written to: /home/safwan/.cache/yay/ros-melodic-python-orocos-kdl/src/build
[ 10%] Generating PyKDL/sipPyKDLpart0.cpp, PyKDL/sipPyKDLpart1.cpp, PyKDL/sipPyKDLpart2.cpp, PyKDL/sipPyKDLpart3.cpp, PyKDL/sipPyKDLpart4.cpp, PyKDL/sipPyKDLpart5.cpp, PyKDL/sipPyKDLpart6.cpp, PyKDL/sipPyKDLpart7.cpp

sip: Deprecation warning: /home/safwan/.cache/yay/ros-melodic-python-orocos-kdl/src/orocos_kinematics_dynamics-1.4.0/python_orocos_kdl/PyKDL/PyKDL.sip:23: %Module version numbers are deprecated and ignored
Scanning dependencies of target python_module_PyKDL
[ 50%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart1.o
[ 50%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart3.o
[ 60%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart4.o
[ 50%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart2.o
[ 50%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart0.o
[ 70%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart5.o
[ 80%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart6.o
[ 90%] Building CXX object CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart7.o
/home/safwan/.cache/yay/ros-melodic-python-orocos-kdl/src/build/PyKDL/sipPyKDLpart1.cpp: In function ‘void assign_ChainJntToJacSolver(void*, Py_ssize_t, void*)’:
/home/safwan/.cache/yay/ros-melodic-python-orocos-kdl/src/build/PyKDL/sipPyKDLpart1.cpp:2124:119: error: use of deleted function ‘KDL::ChainJntToJacSolver& KDL::ChainJntToJacSolver::operator=(const KDL::ChainJntToJacSolver&)’
 2124 |         };
      |                                                                                                                       ^
In file included from /home/safwan/.cache/yay/ros-melodic-python-orocos-kdl/src/orocos_kinematics_dynamics-1.4.0/python_orocos_kdl/PyKDL/kinfam.sip:567:
/opt/ros/melodic/share/orocos_kdl/cmake/../../../include/kdl/chainjnttojacsolver.hpp:41:11: note: ‘KDL::ChainJntToJacSolver& KDL::ChainJntToJacSolver::operator=(const KDL::ChainJntToJacSolver&)’ is implicitly deleted because the default definition would be ill-formed:
   41 |     class ChainJntToJacSolver : public SolverI
      |           ^~~~~~~~~~~~~~~~~~~
...
/opt/ros/melodic/share/orocos_kdl/cmake/../../../include/kdl/chainidsolver_recursive_newton_euler.hpp:40:11: error: non-static reference member ‘const KDL::Chain& KDL::ChainIdSolver_RNE::chain’, cannot use default assignment operator
In file included from /home/safwan/.cache/yay/ros-melodic-python-orocos-kdl/src/orocos_kinematics_dynamics-1.4.0/python_orocos_kdl/PyKDL/dynamics.sip:65:
/opt/ros/melodic/share/orocos_kdl/cmake/../../../include/kdl/chaindynparam.hpp:47:11: error: use of deleted function ‘KDL::ChainIdSolver_RNE& KDL::ChainIdSolver_RNE::operator=(const KDL::ChainIdSolver_RNE&)’
   47 |     class ChainDynParam : SolverI
      |           ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/python_module_PyKDL.dir/build.make:136: CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart2.o] Error 1
make[2]: *** [CMakeFiles/python_module_PyKDL.dir/build.make:110: CMakeFiles/python_module_PyKDL.dir/PyKDL/sipPyKDLpart0.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/python_module_PyKDL.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x56366aec3a60)

**Comment by bionade24** [comment]
We don't support Manjaro. If you would use Arch or EndeavourOS you could use our repo with prebuilt binaries. And please format your code with Markdown next time!

**Comment by acxz** [comment]
@SafwanElmadani Here is a guide by the Manjaro team themeselves on how to convert your Manjaro system to EndeavourOS: https://forum.manjaro.org/t/howto-convert-manjaro-to-endeavouros/155205
