### ISSUE TITLE
Why is ros-melodic-ompl archived?

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-desktop-full#31]
https://github.com/ros-melodic-arch/ros-melodic-ompl has been archived. Is there a particular reason for that? It is inside the upstream [`distribution.yaml`](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml#L6907) and a dependency for a couple of other packages.

**Comment by bionade24** [comment]
It relied on qt4 (which wasn't in the official repos anymore) broken for a long time and no one cared about it, I didn't have the time to care about that. I'll unarchive it as seem to care.
