### ISSUE TITLE
Build and sync current state

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-desktop-full#32]
I've put a lot of effort making (almost) all packages from this organization build in a clean chroot over the last days. Many of them have outstanding PRs which make the packages build.

Before going further and updating the packages, it would be nice to know they are also building in @bionade24's ci pipeline. As I was using my own local repository, I also updated and added dependencies that might not be in the [oscloud repo](http://repo.oscloud.info/). So, in order to completely build the current state, it might be necessary to update packages there or add dependencies. The upstream dependencies I used are:

 * console-bridge-1.0.1-1/
 * cwiid-svn_history-3/
 * eigenpy-2.5.0-1/
 * fcl-0.6.1-1/
 * flann-1.9.1-7/
 * gazebo-11.0.0-1/
 * geographiclib-1.50.1-1/
 * ignition-cmake-2.2.0-1/
 * ignition-common-3.5.0-1/
 * ignition-fuel_tools-4.1.0-2/
 * ignition-math-6.4.0-6/
 * ignition-msgs-5.2.0-1/
 * ignition-tools-1.0.0-2/
 * ignition-transport-8.0.0-3/
 * libccd-2.1-1/
 * libxml-1.8.17-1/
 * octomap-1.9.5-1/
 * ogre-1.9-1.9.1-4/
 * ogre-docs-1.9-1.9.1-4/
 * ompl-1.5.0-1/
 * opencv3-opt-3.4.11-1/
 * opencv3-opt-samples-3.4.11-1/
 * openni-1.5.7.10-6/
 * openni2-2.2.0-1/
 * pcl-1.11.1-1/
 * python-backports.ssl-0.0.9-1/
 * python-bson-0.5.8-1/
 * python-catkin_pkg-0.4.14-1/
 * python-pyassimp-5.0.1-1/
 * python-rosdep-0.19.0-2/
 * python-rosdistro-0.8.2-2/
 * python-rospkg-1.2.8-1/
 * python-tornado-4-4.5.3-2/
 * qtcreator-src-4.12.4-1/
 * sdformat-9.2.0-2/
 * spacenavd-0.7.1-1/
 * tango-icon-theme-0.8.90-14/
 * urdfdom-1.0.4-4/
 * urdfdom-headers-1.0.4-1/
 * ros-melodic-octomap-ros-0.4.0/ (package by majorx234)
 * ros-melodic-octomap-server-0.6.5/ (package by majoxr234)
 * ros-melodic-robotnik-msgs-1.0.0 (package by majoxr234, with local modifications)
 * ros-melodic-twist-mux-3.1.1 (package by majoxr234, with local modifications)
 * ros-melodic-twist-mux-msgs-2.1.0 (package by majoxr234, with local modifications)

I was not sure how to proceed with the ROS packages not managed by us. Should I add them inside this organization and we poke the maintainer to hand it over (as done with `effort_controllers` and `velocity_controllers`)?

The only packages currently not building are
 * qtcreator-ros (I did not bother fixing this after fixing a couple of issues and still getting errors)
 * ros-melodic-moveit-experimental (has been split up upstream. I did not care too much for it, as it isn't inside the upstream distribution)
 * ros-melodic-opencv3 (What's that for, anyway)
 * ros-melodic-octovis (qt4 issues, see https://github.com/ros-melodic-arch/ros-melodic-octovis/issues/1)

If everything is fine in the current state, I'd go ahead and update the packages to their released versions as a next step. Any comments up to this point @bionade24?

**Comment by fmauch** [comment]
I've started updating a lot of packages, so a build & sync by @bionade24 would probably be quite good.

**Comment by bionade24** [comment]
Sync should be better now.
