### ISSUE TITLE
Signature Invalid (again?)

### ISSUE THREAD

**Issue by t3pfaffe** [ros-melodic-arch/ros-melodic-desktop-full#33]
Getting an error specifically on console-bridge. However it could be on other packages as well. This is jus the first pacman ran into.

```
error: console-bridge: signature from "Oskar Roesler (Username: bionade24) <o.roesler@oscloud.info>" is invalid
:: File /var/cache/pacman/pkg/console-bridge-1.0.1-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

**Comment by bionade24** [comment]
Will look into it. Reimplemented CI/CD and used a new tool for repo-add and signing at once. Packages dependent on console-bridge just build fine. CI status: https://abs-cd.oscloud.info 

Am Samstag, 19. September 2020 schrieb Tom Pfaffe:

**Comment by bionade24** [comment]
I tried an everything was fine for me. Try to clean your pacman db (`pacman -Scc`).

**Comment by bionade24** [comment]
@t3pfaffe Could you solve it or is it still there? If so, maybe I can help.

**Comment by t3pfaffe** [comment]
Yes it works for me now. Could have been on my end. I guess I just jumped to the assumption that it wasn't since I previously had issues with ROS on Arch with the signatures.

**Comment by bionade24** [comment]
No Problem. Seems like we won't have these issues again with the new tool.

Am Donnerstag, 24. September 2020 schrieb Tom Pfaffe:
