### ISSUE TITLE
Signature Invalid while updating repo

### ISSUE THREAD

**Issue by victor-botsync** [ros-melodic-arch/ros-melodic-desktop-full#34]
![image](https://user-images.githubusercontent.com/66936018/120415769-ac64ed80-c38e-11eb-9796-e744b16b5eab.png)

I am having this error today suddenly while I was trying to update my repos. It was working fine yesterday. Is the key changed?

> error: oscloud: signature from "Oskar Roesler (Username: bionade24) <o.roesler@oscloud.info>" is invalid
> error: failed to update oscloud (invalid or corrupted database (PGP signature))
> error: failed to synchronize all databases

**Comment by bionade24** [comment]
Hello, nothing changed. I messed up while using `repo-remove`. Should be 
fine again now.
