### ISSUE TITLE
Rospack error while loading shared libraries: libtinyxml2.so.7

### ISSUE THREAD

**Issue by victor-botsync** [ros-melodic-arch/ros-melodic-desktop-full#35]
![image](https://user-images.githubusercontent.com/66936018/122018783-c1616800-cdf5-11eb-973c-0d9b0787fadf.png)
I think the latest AUR update on the tinyxml2 broke the rospack and rosstack function.

**Comment by fmauch** [comment]
How did you installROS? Using the binary package from oscloud or did you build it from scratch (from AUR directly)?

In the latter case you can rebuild the packages yourself, see [here](https://wiki.archlinux.org/title/ROS#Rebuild_when_shared_libraries_are_updated)

@bionade24 we should probably trigger a tree rebuild for melodic-desktop-full in the CI, right?

**Comment by victor-botsync** [comment]
I did it using the AUR method. Okay, I will try using the method mentioned.

**Comment by victor-botsync** [comment]
How do I rebuild the packages that are listed in the python script?

**Comment by fmauch** [comment]
`yay -S --rebuild <package 1> <package 2> <package 3>...`

I'm not sure what the exact output of that script is, as I have a modified version on my machine. I've put it [here](https://gist.github.com/fmauch/bb1d05592fa33fefac2dc5062876226f). With that I can just copy the one line containing all packages and add it to `yay -S --rebuild`

**Comment by victor-botsync** [comment]
![image](https://user-images.githubusercontent.com/66936018/122039704-8701c600-ce09-11eb-8be3-5f5ef22db75d.png)
I am still getting the same issue. Sorry I am new to Arch and not sure of many things. I have also restarted the system to see if that is needed to  get it go work but it seems not.

**Comment by fmauch** [comment]
rostack is not inside our AUR distribution, so that might be why, you'll have to rebuild that, as well (depending on how you installed it in the forst place, probably rebuild your workspace (as in delete build & devel and rebuild)?)

**Comment by victor-botsync** [comment]
I managed to get it fixed by uninstalling all ROS packages and reinstalling them again. Will take note of the installation method and will try your method again next time.

**Comment by bionade24** [comment]
Sorry for my late response. 
> @bionade24 we should probably trigger a tree rebuild for melodic-desktop-full in the CI, right?

Probably, can't hurt. Will do.

> I think the latest AUR update on the tinyxml2 broke the rospack and rosstack function.

That can happen with AUR packages if dependencies get updated and the other package doesn't increase `pkgrel`. E.g, we don't track this properly. If you yay, do `yay -S --rebuildtree ros-melodic-desktop-full` and you'll be fine afterwards. Yeah, we should do better in tracking deps, but it's just extremely hard doing that for that many deps as all those ros packages have.
