### ISSUE TITLE
ERROR: Remote key not fetched correctly from keyserver

### ISSUE THREAD

**Issue by Tambup** [ros-melodic-arch/ros-melodic-desktop-full#36]
Hi,

I just read [this issue](https://github.com/ros-melodic-arch/ros-melodic-ros-base/issues/3), but the solution does not work. I always get the same error:
```
ERROR: Remote key not fetched correctly from keyserver
```

Namely, the error persist using:
`sudo pacman-key --recv-keys CB222E7EBC11D682AAC8B317A4A0D73114FDE6FC --keyserver keyserver.ubuntu.com`.

Another interesting point is that doing `sudo pacman -Syy` after adding the repo in `pacman.conf`, than pacman suggests me `:: Import PGP key 289AD6AA32857A04ABA587417EAC11ACDBCFBCEB? [Y/n]`.

The system is up to date. I read in the cited issue that should be fixed, but the problem seems persisting.

I also suggest, if possible, to add to the [arch unofficial repos page](https://wiki.archlinux.org/title/Unofficial_user_repositories#oscloud) the used keyserver.

Thanks for support.

**Comment by Tambup** [comment]
I have further information:
searching the key in the browser [keyserver.ubuntu.com](keyserver.ubuntu.com) gives "Not Found".

**Comment by bionade24** [comment]
R you sure your GPG is fine? You can also search on the keyservers for my mail address and try to use the shoeyer fingerprint. I haven't changed anything about my key since so should be fine from my side.

**Comment by bionade24** [comment]
Have you signed my key locally? Otherwise pacman doesn't trust it.

**Comment by Tambup** [comment]
Finally found the problem, is quite weird:
i changed the DNS server (editing /etc/resolv.conf) and now it works. Also, it wasn't necessary to specify the keyserver. 

So, i close the issue. Anyway, thanks for support.

**Comment by bionade24** [comment]
You may will have some issues with the repo, but I'll fix them in the next days. See https://abs-cd.oscloud.info/ for build dates and details.

**Comment by Tambup** [comment]
Yes, i see. Minor issues anyway, you did a great job imho.

I report you that rosout is built with liblog4cxx.so.12, but in your repo there is only liblog4cxx.so.10. I solved installing liblog4cxx.so.12 from community repo. I write if someone have the same problem.
