### ISSUE TITLE
[Package Request] Turtlebot3

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-desktop-full#4]
Hello! I will be working on the turtlebot3 system soon and I noticed that there are no `turtlebot3` packages.

As of now I will require the following ros packages:
`ros-melodic-turtlebot3`: https://wiki.ros.org/turtlebot3
`ros-melodic-turtlebot3-msgs`: https://wiki.ros.org/turtlebot3_msgs
`ros-melodic-turtlebot3-simulations`: https://wiki.ros.org/turtlebot3_simulations

I am not sure how I should go about creating these packages.

**Comment by jwhendy** [comment]
I would use the following process, using `turtlebot3_msgs` as the example:
- find the package on [rosindex](http://rosindex.github.io/), if possible (looks not to exist, so perhaps the team hasn't published to rosdistro to get on the radar)
- if you can't get the melodic version on rosindex, look on the [repo releases](https://github.com/ROBOTIS-GIT/turtlebot3_msgs/releases). Thankfully they state that 2.x is ROS2, so I'd take the last non-ROS2 version... in this case 1.0.0
- use a previous PKGBUILD as your starting point; they look pretty similar to me, but not sure. Fill in wiki, version, pkgrel, _dir, etc.
- use the package.xml to figure out the dependencies, either for make (build or test depend) or true depends (depends). I think `ros-build-tools`, `catkin`, `cmake`, etc. are always going to be required.

Then try to build! :) I [started with turtlebot3_msgs](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-msgs) and this procedure worked. Whether or not it actually works for the turtlebot3 is a different story!

Want to clone and build that repository, then modify for turtlebot3_simulations and turtlebot3?

Once it's created here, I think it's up to @bionade24 on how to get it on AUR. I haven't done anything with AUR yet.

**Comment by jwhendy** [comment]
Oh, and I don't know how @bionade24 created permissions here, but I was able to create a new repository and just push there. That doesn't guarantee it makes it to AUR, but I'm sure that's fairly trivial.

**Comment by acxz** [comment]
I see, thanks for your guidance. I will try to create the rest of the turtlebot3 packages.

**Comment by acxz** [comment]
I'll keep this repo up until the specified packages are pushed to the AUR.

**Comment by acxz** [comment]
@bionade24 The following is the list of repositories that I have created/modified in order to resolve this issue. If these repos can be pushed into the AUR soon, it would be much appreciated so that I can test them out on an actual Turtlebot3 in addition to my own development computer. Thank you.

- [ ] [ros-melodic-turtlebot3](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3)
- [ ] [ros-melodic-turtlebot3-navigation](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-navigation)
- [x] [ros-melodic-turtlebot3-teleop](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-teleop)
- [ ] [ros-melodic-turtlebot3-slam](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-slam)
- [ ] [ros-melodic-turtlebot3-simulations](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-simulations)
- [x] [ros-melodic-turtlebot3-msgs](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-msgs)
- [ ] [ros-melodic-turtlebot3-gazebo](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-gazebo)
- [x] [ros-melodic-turtlebot3-fake](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-fake)
- [ ] [ros-melodic-turtlebot3-example](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-example)
- [x] [ros-melodic-turtlebot3-description](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-description)
- [ ] [ros-melodic-turtlebot3-bringup](https://github.com/ros-melodic-arch/ros-melodic-turtlebot3-bringup)
- [x] [ros-melodic-rosserial-python](https://github.com/ros-melodic-arch/ros-melodic-rosserial-python)
- [x] [ros-melodic-rosserial-msgs](https://github.com/ros-melodic-arch/ros-melodic-rosserial-msgs)
- [x] [ros-melodic-hls-lfcd-lds-driver](https://github.com/ros-melodic-arch/ros-melodic-hls-lfcd-lds-driver)

**Comment by bionade24** [comment]
Sorry, I'm ill these days. Will do it with the new PKGBUILDs next week when I feel better.

**Comment by acxz** [comment]
Np, I hope you feel better soon!

**Comment by acxz** [comment]
@bionade24 do you have an ETA on when you will perform a sync with this organization and the AUR? It would be nice if we can get these new package, turtlebot3 and rosbridge, along with the fixes to cv-bridge and moveit-core out to the public.

**Comment by bionade24** [comment]
I currently rewrite my test CI/CD and have to fix one issue in a SW it depends on. Probably tomorrow or Wednesday.

**Comment by acxz** [comment]
I have created the missing packages in the AUR.

@bionade24 Please email me for transfer ownership, Sorry for the inconvenience this may have caused. I have added you as a co-maintainer, will disown when a) you have emailed me or b) when I am done testing these packages (~ 1 month)
