### ISSUE TITLE
Update/Create Melodic Packages Based on Upstream

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-desktop-full#5]
Hey guys, another update for ROS Melodic is out: https://discourse.ros.org/t/new-packages-for-melodic-2019-11-05/11361

As such, I am creating this thread to update and create new packages as necessary to get this Melodic update out on Arch.

Tasks:
Create new packages from the list if they do not exist
Update packages from the list if they do

I am not sure on what is the best way to track this besides creating a check box list of all new the packages here and creating issues for updating the older ones. Or we can just wing it.

**Comment by bionade24** [comment]
If you could make a project with goals for it, it would be perfect. I'm currently very busy and don't even have much time to fix the build issues in my CI.

**Comment by bionade24** [comment]
https://github.com/orgs/ros-melodic-arch/projects

**Comment by acxz** [comment]
Sure, that's a good idea.
Yeah I figured as much, don't worry. Hope you get to relax soon.
