### ISSUE TITLE
Unable to install with python2

### ISSUE THREAD

**Issue by TinfoilSubmarine** [ros-melodic-arch/ros-melodic-desktop-full#6]
I am trying to get an install of Melodic running with python2, since our codebase is using python2, but all of the packages use python3 versions of everything.

**Comment by jwhendy** [comment]
My initial thought is [this](https://pythonclock.org/), but I also don't know how long groups plan to stay on py2 after the end of life declaration.

I'd be interested to hear perspectives from @bionade24 and @acxz on this, but trying to maintain both versions seems daunting to me (particularly after recently updating every package to use upstream sources and deal with boost 1.71).

We would have to test builds twice for every package and figure out a robust way to deal with this in our scripts. As in, we have versions hard coded in to remove the ambiguity of some packages just calling `python` (vs versioned equivalents). We would need an overhaul to detect the right version or let the user specify.

Any thoughts based on these areas of hesitation? And could you share your team's long term py2 plan so we have a ballpark understanding of the impact?

**Comment by acxz** [comment]
I agree with @jwhendy , with around 2 months left of python2 maintenance, there is no reason for us to accommodate python2. If anything the next ROS release, Noetic, will be all Python 3. Compiling and using python 3 with Melodic, allows the Arch community contribute back to ROS and help the ROS Noetic release. I would urge your existing codebase to be updated or to look at ROS Kinetic on Arch Linux if you really need a python 2 ROS version.

**Comment by bionade24** [comment]
Simple nodes should work fine, but supporting python2 would be unnecessary effort. Someone who wants to use all python capabilities with python2 needs something debian-based or can patch the PKGBUILDs itself. Arch will drop py2 support ASAP, so switching to something Debian-based would be smart, then you'll even get  support afterwards.

Am Freitag, 8. November 2019 schrieb John Hendy:

**Comment by acxz** [comment]
Going ahead and closing this. please reopen if you would like to still discuss this issue.
